#page title
page_title                                : Only Up!

# App Info
ios_app_id                                : 6450400097
ios_app_country                           : us
appstore_link                             : https://apps.apple.com/us/app/only-up-dont-fall/id6450400097
playstore_link                            : https://play.google.com/store/apps/details?id=com.whitelab.onlyjumpup&gl=VN
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      
app_name                                  : Only Up : don't fall!
app_price                                 : Free
app_description                           : The world is undoubtedly in a state of turmoil, but it's important to acknowledge that it has never been entirely stable. Nevertheless, the present circumstances could be viewed as an opening for you to make a positive impact. When faced with a crisis, it's essential to take action and make decisive choices, even though doing so can be frightening since every step carries the potential to set you back.

enable_smart_app_banner                   : true


# Information About Yourself
your_name                                 : Ionita Serghei                              
your_link                                 : https://linkyy.co/whitelab                 
your_city                                 : WorldWide                                
email_address                             : ionita12@mail.ru
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : only-Up
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Only Up
    description                           : Move forward only up, never down, best parkour game ever.
    fontawesome_icon_name                 : magic
    
  - title                                 : Cross Platform Mobile support
    description                           : The app is published on iOS and Android 
    fontawesome_icon_name                 : mobile

  - title                                 : Fremium game
    description                           : The game contains ads, but it is absolute free.
    fontawesome_icon_name                 : gamepad



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
